### ISSUE TITLE
Allow amber.yaml file to be searched in parent directory

### ISSUE THREAD

**Issue by psibi** [fpco/amber#21]
Right now amber by default checks `amber.yaml` in the directory where
the command is being executed.

I think it might be convenient if it searches it's parent directory
too. I found that this could be convenient in one of the recent
projects I integrated amber with.

So I think for finding the amber.yaml, we can slightly change it to
accommodate something like this:

- check if the passed location (either default or explicitly passed value) of file exists and use that if found.
- If not, traverse your parent directory to see if it exists

I would be happy to implement it in the coming days, if you aren't
opposed to it.

**Comment by snoyberg** [comment]
Overall sounds good. However, I’d recommend that this logic does not apply if the user explicitly passes in a file location.
