### ISSUE TITLE
Github marketplace action for amber

### ISSUE THREAD

**Issue by chrisjsimpson** [fpco/amber#26]
Would make amber easier to consume in the GitHub ecosystem (without requiring any changes to amber)

A developer using Github actions would not need to worry about how to install amber e.g. https://github.com/chrisjsimpson/amber-secrets-ci-example/blob/9854d92efd11bccb1919f8f74e9a38e5cbec6cd0/.github/workflows/production.yml#L19-L22 would be abstracted away.

Have some [experience](https://github.com/chrisjsimpson/droplet-rebuild-action) with this.

**Comment by snoyberg** [comment]
No objection from me if someone wants to take it on.

**Comment by psibi** [comment]
Github marketplace action is available now: https://github.com/fpco/amber#github-actions 

So probably this issue can be closed ?
